version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: centre_formation_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: centre_formation
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: centre_formation_phpmyadmin
    environment:
      PMA_HOST: database
    ports:
      - "8080:80"
    depends_on:
      - database

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: centre_formation_php
    volumes:
      - ./symfony:/var/www/symfony
    depends_on:
      - database

  nginx:
    image: nginx:stable-alpine
    container_name: centre_formation_nginx
    ports:
      - "80:80"
    volumes:
      - ./symfony:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

networks:
  default:
    name: centre_formation_network
